name: Actualización diaria de datos REE

on:
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 02:00 UTC
  workflow_dispatch:  # Permite ejecutarlo manualmente desde GitHub

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar actualización
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python script_extraction_and_update.py
